function Footer() {
  return (
    <div className="footer">
      <p>
        <strong>Generated by:</strong> Computational forensics analysis<br/>
        <strong>Last Updated:</strong> January 2025<br/>
        <strong>Analysis Version:</strong> 2.0 (React)
      </p>
      <p style={{ marginTop: '15px' }}>
        <a href="https://www.wired.com/story/metadata-shows-the-dojs-raw-jeffrey-epstein-prison-video-was-likely-modified/" target="_blank" rel="noopener noreferrer">
          Original Wired Article
        </a>
        {' | '}
        <a href="https://www.justice.gov/opa/media/1407001/dl?inline" target="_blank" rel="noopener noreferrer">
          DOJ Video Release
        </a>
        {' | '}
        <a href="https://exiftool.org/" target="_blank" rel="noopener noreferrer">
          ExifTool Documentation
        </a>
        {' | '}
        <a href="https://ffmpeg.org/documentation.html" target="_blank" rel="noopener noreferrer">
          FFmpeg Documentation
        </a>
      </p>
      <p style={{ marginTop: '15px', fontSize: '0.9rem', color: '#666' }}>
        This project is released under the MIT License. 
        All analysis tools and methods are open source and available for independent verification.
      </p>
    </div>
  )
}

export default Footer

